version: '3.7'

services:

  redis:
    image: redis:5.0.7
    container_name: db2_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  sender:
    build: .
    image: db2_python:0.0.1
    container_name: db2_sender
    restart: always
    volumes:
      - ./:/app
